config/routes.rb
# == Route Map
#
#        Prefix Verb   URI Pattern                   Controller#Action
#     questions GET    /questions(.:format)          questions#index
#               POST   /questions(.:format)          questions#create
#  new_question GET    /questions/new(.:format)      questions#new
# edit_question GET    /questions/:id/edit(.:format) questions#edit
#      question GET    /questions/:id(.:format)      questions#show
#               PATCH  /questions/:id(.:format)      questions#update
#               PUT    /questions/:id(.:format)      questions#update
#               DELETE /questions/:id(.:format)      questions#destroy
#

Rails.application.routes.draw do
  root :to => 'questions#index'

  get '/about' => 'pages#about'

  resources :questions do
    resources :answers, :only => [:create, :update, :edit, :destroy], :controller => 'questions/answers' do
      get '/voteup' => 'a_votes#up'
      get '/votedown' => 'a_votes#down'
    end
    get '/voteup' => 'q_votes#up'
    get '/votedown' => 'q_votes#down'
  end

  get '/users/edit' => 'users#edit'
  resources :users, :only => [:new, :create, :edit, :update, :show]

  get '/signup' => 'users#new'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

#  post '/answers' => 'answers#create'
#  post '/answers/:id' => 'answers#update'
#  delete '/answers' => 'answers#delete'

end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  title      :text
#  text       :text
#  score      :integer
#  edited_at  :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question < ActiveRecord::Base
  has_many :answers, :dependent => :destroy
  belongs_to :user
  has_many :q_votes, :dependent => :destroy

  validates :user, :presence => true
  validates :title, :length => { :in => 6..50 }
  validates :text, :length => { :in => 6..5000 }
end

app/controllers/questions/answers_controller.rb
class Questions::AnswersController < ApplicationController

  before_filter :answer_ownership, :except => :create
  before_filter :check_logged_in, :only => :create
  after_action :get_q_vote, :except => [:destroy]

  def create
    @answer = Answer.new answer_params
    @question = Question.find params[:question_id]
    @answer.question = @question
    @answer.score = 1
    @answer.user= @current_user
    if @answer.save
      redirect_to @question
    else
      before_render
      render '/questions/show'
    end
  end

  def edit # @question and @answer are loaded by the before filter.
    before_render
    render '/questions/show'
  end

  def update
    @answer.update answer_params
    unless @answer.errors.any?
      @answer.edited_at = @answer.updated_at
      @answer.save
      before_render
      redirect_to @question
    else
      before_render
      render '/questions/show'
    end
  end

  def destroy
    @answer.destroy
    # Yeah, trying to learn ajax in one night when the ruby docs are in coffeescript, non trivial.
    # respond_to do |format|
    #   format.html { redirect_to question_path }
    #   format.json { head :no_content }
    # end
    redirect_to @question
  end

  private
  def answer_params
    params.require(:answer).permit(:text)
  end

  def answer_ownership
    @question = Question.find params[:question_id]
    @answer =@question.answers.find params[:id]
    unless @answer.user == @current_user
      flash[:error] = "ಠ_ಠ don't edit what isn't yours ಠ_ಠ"
      redirect_to root_path
    end
  end

  def before_render #if anyone can explain to me why this isn't in rails, you can go fuck yourself.
    # and yes, I know about the gem, thankyou. I'm doing this at fucking 2am on friday and don't
    # want a deploy issue.
    @answers = @question.answers
    get_votes
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_filter :question_ownership, :only => [:edit, :update, :destroy]
  before_filter :check_logged_in, :only => [:new, :create]

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find params[:id]
    @answer = Answer.new
    @answers = @question.answers
    get_votes
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new question_params
    @question.score = 1
    @question.user = @current_user
    if @question.save
      redirect_to @question
    else
      render :new
    end
  end

  def edit
  end

  def update
    @question.update question_params
    unless @question.errors.any?
      @question.edited_at = @question.updated_at
      @question.save
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions
  end

  private
  def question_params
    params.require(:question).permit(:id, :title, :text)
  end

  def question_ownership
    @question = Question.find params[:id]
    unless @question.user == @current_user
      flash[:error] = "ಠ_ಠ don't edit what isn't yours ಠ_ಠ"
      redirect_to root_path
    end
  end

end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/questions/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">

<%= form_for @question do |f| %>

  <% if @question.errors && @question.errors[:user].any?%>
    <p>
      <%= @user.errors[:user].join(', ') %>
    </p>
  <% end %>

  <fieldset class="unbordered">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "form-control" %>

    <% if @question.errors && @question.errors[:title].any?%>
      <span>
        <%= @question.errors[:title].join(', ') %>
      </span>
    <% end %>
  </fieldset>
  <fieldset class="unbordered">
    <%= f.label :text %>
    <%= f.text_area :text, :class => "form-control", :rows => "6" %>

    <% if @question.errors && @question.errors[:text].any?%>
      <span>
        <%= @question.errors[:text].join(', ') %>
      </span>
    <% end %>
  </fieldset>
  <%= f.submit "Ask Your Question", :class => ["btn", "btn-primary", "btn-lg"]  %>
<% end %>
</div>
</div>
</div>

app/views/questions/_q_score.html.erb
<div class="q_score_bag col-xs-2 text-center">

  <% if @q_vote.nil? %>
    <% up_class_string = "grey up" %>
    <% down_class_string = "grey down" %>
  <% elsif @q_vote.valency == 1 %>
    <% up_class_string = "yellow up" %>
    <% down_class_string = "grey down" %>
  <% elsif @q_vote.valency == -1 %>
    <% up_class_string = "grey up" %>
    <% down_class_string = "yellow down" %>
  <% end %>

  <%= link_to '‽', question_voteup_path(@question.id), :class => up_class_string %>
  </br>
  <span class="blue score">
    <%= @question.score %>
  </span>
  <br>
  <%= link_to '¿', question_votedown_path(@question.id), :class => down_class_string %>

</div>

app/views/questions/_q_toolbar.html.erb
<% if  @current_user == @question.user %>
  <span>
    &nbsp; <%= link_to edit_question_path(@question.id) do %>
      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
    <% end %>
  </span>
  <% unless @question.answers.any? or @question.score > 2 %>
    <span>
      &nbsp; <%= link_to(
                  @question,
                  :method => 'delete',
                  :data => {:confirm => 'Delete Your Question?'}) do %>
        <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span>
      <% end %>
    </span>
  <% end %>
<% end %>

app/views/questions/edit.html.erb
<h1 class="text-center question-form-heading">Edit Question</h1>

<%= render :partial=> 'form' %>

app/views/questions/index.html.erb
<div class="container qi">

  <h1 class="qi--title"> Questions </h1>

  <% @questions.sort {|a, b| b.score <=> a.score }.each do |q| %>

    <a href="/questions/<%= q.id %>">
      <div class="qi--question row">
        <div class="col-xs-2 q_score_bag text-center">
          <p class="blue score">
            <%= q.score %>
          </p>

        </div>

        <div class="col-xs-10">
          <span class="qi--question--title">
            <%= q.title %>
          </span>

        </div>
        <div class="qi--date-positioner">
          <%= render :partial => '/layouts/verbed_by',
                     :locals => {:verbed => "asked", :timeable => q, :unlinked => true} %>
        </div>


      </div>
    </a>
    <hr>

  <% end %>
</div>

app/views/questions/new.html.erb
<h1 class="text-center question-form-heading"> New Question </h1>

<%= render :partial=> 'form' %>

app/views/questions/show.html.erb
<div class="col-xs-1"></div>
  <div class="container col-xs-10">
    <div class="question--show row clearfix">
      <%= render :partial => 'questions/q_score'  %>
      <div class="col-xs-10">
        <div class="clearfix">
          <div class="pull-right">
            <%= render :partial => '/questions/q_toolbar' %>
          </div>
          <span class="question--title"> <%= @question.title %> </span>
        </div>

        <article class="question--text">
          <%= markdown @question.text %>
        </article>

        <%= render :partial => '/layouts/verbed_by',
                   :locals => {:verbed => "asked", :timeable => @question, :unlinked => false} %>
      </div>
    </div>

    <hr class="double--top"><hr class="double--bottom">

    <% if @answers.size > 0 %>
      <h3><%= pluralize(@answers.size, 'Answer')%></h3>
    <% else %>
      <h3>No Answers Yet</h3>
    <% end %>
    <%= render :partial => '/questions/answers/index' %>


  </div>
<div class="col-xs-1"></div>