config/routes.rb
# == Route Map
#
#        Prefix Verb   URI Pattern                   Controller#Action
#     questions GET    /questions(.:format)          questions#index
#               POST   /questions(.:format)          questions#create
#  new_question GET    /questions/new(.:format)      questions#new
# edit_question GET    /questions/:id/edit(.:format) questions#edit
#      question GET    /questions/:id(.:format)      questions#show
#               PATCH  /questions/:id(.:format)      questions#update
#               PUT    /questions/:id(.:format)      questions#update
#               DELETE /questions/:id(.:format)      questions#destroy
#

Rails.application.routes.draw do
  root :to => 'questions#index'

  get '/about' => 'pages#about'

  resources :questions do
    resources :answers, :only => [:create, :update, :edit, :destroy], :controller => 'questions/answers' do
      get '/voteup' => 'a_votes#up'
      get '/votedown' => 'a_votes#down'
    end
    get '/voteup' => 'q_votes#up'
    get '/votedown' => 'q_votes#down'
  end

  get '/users/edit' => 'users#edit'
  resources :users, :only => [:new, :create, :edit, :update, :show]

  get '/signup' => 'users#new'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

#  post '/answers' => 'answers#create'
#  post '/answers/:id' => 'answers#update'
#  delete '/answers' => 'answers#delete'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  password_digest :text
#  name            :text
#  email           :text
#  avatar          :text
#  link            :text
#  bio             :text
#  points          :integer
#  hide_state      :integer
#  admin           :integer
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  has_many :questions
  has_many :answers
  has_many :q_votes

  has_secure_password
  validates :email, :presence => true, :uniqueness => true
  validates :name, :presence => true, :uniqueness => true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :login_check, :except => [:new, :create]

  def new
    @user = User.new
  end

  def show
    @user = User.find params[:id]
  end

  def create
    @user = User.new user_params
    @user.points = 1
    @user.hide_state = 0
    @user.admin = 0
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = @current_user
  end

  def update
    @user = @current_user
    if @user.update user_params
      redirect_to @current_user
    else
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :avatar,
      :link,
      :bio,
      :password,
      :password_confirmation
    )
  end

  def login_check
    unless @current_user
      flash[:error] = "You can't view that unless you're logged in"
      redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="middle-form">
  <h1 class="text-center form-heading">Edit Profile</h1>

  <%= form_for @user do |f| %>
    <fieldset>
      <strong>You're stuck with your username, sorry.</strong>
    </fieldset>
    <fieldset>
      <%= f.label :email %>
      <%= f.email_field :email, :class => "form-control" %>
      <% if @user.errors.any? && @user.errors[:email].any?%>
        <span>
          <%= @user.errors[:email].join(', ') %>
        </span>
      <% end %>

    </fieldset>
    <!--<fieldset>  this should be on a separate page, but I never wrote it.
      <%= f.label :password %>
      <%= f.password_field :email %>
    </fieldset>
    <fieldset>
      <%= f.label :confirm_password %>
      <%= f.password_field :confirm_password %>
    </fieldset> -->
    <fieldset>
      <%= f.label :avatar %>
      <%= f.text_field :avatar, :class => "form-control" %>

      <% if @user.errors && @user.errors[:avatar].any?%>
        <span>
          <%= @user.errors[:avatar].join(', ') %>
        </span>
      <% end %>
    </fieldset>

    <fieldset>
      <%= f.label :link %>
      <%= f.url_field :link, :class => "form-control" %>

      <% if @user.errors && @user.errors[:link].any?%>
        <span>
          <%= @user.errors[:link].join(', ') %>
        </span>
      <% end %>
    </fieldset>

    <fieldset>
      <%= f.label :bio %>
      <%= f.text_area :bio, :class => "form-control", :rows => "4" %>

      <% if @user.errors && @user.errors[:bio].any?%>
        <span>
          <%= @user.errors[:bio].join(', ') %>
        </span>
      <% end %>
    </fieldset>
    <div class="btn-wrapper">
      <%= f.submit 'Save Changes', :class => "btn btn-primary btn-lg" %>
    </div>
</div>
<% end %>

app/views/users/new.html.erb
<div class="middle-form">
  <h1 class="text-center form-heading">Sign up!</h1>

  <%= form_for @user do |f| %>
    <fieldset>
      <%= f.label :name, 'Username' %>
      <%= f.text_field :name, :required => true, :class => "form-control" %>
      <% if @user.errors.any? && @user.errors[:name].any?%>
        <span>
          <%= @user.errors[:name].join(', ') %>
        </span>
      <% end %>

    </fieldset>
    <fieldset>
      <%= f.label :email %>
      <%= f.email_field :email, :required => true, :class => "form-control" %>
      <% if @user.errors.any? && @user.errors[:email].any?%>
        <span>
          <%= @user.errors[:email].join(', ') %>
        </span>
      <% end %>

    </fieldset>
    <fieldset>
      <%= f.label :password %>
      <%= f.password_field :password, :required => true, :class => "form-control"  %>
      <% if @user.errors.any? && @user.errors[:password].any?%>
        <span>
          <%= @user.errors[:password].join(', ') %>
        </span>
      <% end %>

    </fieldset>
    <fieldset>
      <%= f.label :password_confirmation%>
      <%= f.password_field :password_confirmation, :required => true, :class => "form-control"  %>
      <% if @user.errors.any? && @user.errors[:password_confirmation].any?%>
        <span>
          <%= @user.errors[:password_confirmation].join(', ') %>
        </span>
      <% end %>

    </fieldset>
    <div class="btn-wrapper">
      <%= f.submit 'Join us', :class => "btn btn-primary btn-lg"  %>
    </div>
  </div>

<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-9 col-xs-offset-2">
      <h3 class="user--show--heading"><%= @user.name %></h3>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <% if @user.avatar.present? %>
        <%= image_tag @user.avatar, :class => "margin-0-auto-rounded"%>
      <% end %>
      <dl class="dl-horizontal">
        <dt> email </dt>
        <dd> <%= @user.email %> </dd>

        <% if @user.link.present? %>
          <dt> link </dt>
          <dd> <%= @user.link %> </dd>
        <% end %>

        <% if @user.bio.present? %>
          <dt> bio </dt>
          <dd> <%= @user.bio %> </dd>
        <% end %>
      </dl>
    </div>
  </div>


  <% if @user == @current_user %>
    <div class="middle-form">
      <%= link_to "Edit Profile?", users_edit_path(@current_user), :class => ["btn", "btn-primary", "btn-lg"]%>
    </div>
  <% end %>
</div>