config/routes.rb
# == Route Map
#
#        Prefix Verb   URI Pattern                   Controller#Action
#     questions GET    /questions(.:format)          questions#index
#               POST   /questions(.:format)          questions#create
#  new_question GET    /questions/new(.:format)      questions#new
# edit_question GET    /questions/:id/edit(.:format) questions#edit
#      question GET    /questions/:id(.:format)      questions#show
#               PATCH  /questions/:id(.:format)      questions#update
#               PUT    /questions/:id(.:format)      questions#update
#               DELETE /questions/:id(.:format)      questions#destroy
#

Rails.application.routes.draw do
  root :to => 'questions#index'

  get '/about' => 'pages#about'

  resources :questions do
    resources :answers, :only => [:create, :update, :edit, :destroy], :controller => 'questions/answers' do
      get '/voteup' => 'a_votes#up'
      get '/votedown' => 'a_votes#down'
    end
    get '/voteup' => 'q_votes#up'
    get '/votedown' => 'q_votes#down'
  end

  get '/users/edit' => 'users#edit'
  resources :users, :only => [:new, :create, :edit, :update, :show]

  get '/signup' => 'users#new'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

#  post '/answers' => 'answers#create'
#  post '/answers/:id' => 'answers#update'
#  delete '/answers' => 'answers#delete'

end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  question_id :integer
#  user_id     :integer
#  text        :text
#  score       :integer
#  edited_at   :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user

  validates :user, :presence => true
  validates :text, :length => { :in => 6..5000 }
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  title      :text
#  text       :text
#  score      :integer
#  edited_at  :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question < ActiveRecord::Base
  has_many :answers, :dependent => :destroy
  belongs_to :user
  has_many :q_votes, :dependent => :destroy

  validates :user, :presence => true
  validates :title, :length => { :in => 6..50 }
  validates :text, :length => { :in => 6..5000 }
end

app/controllers/questions/answers_controller.rb
class Questions::AnswersController < ApplicationController

  before_filter :answer_ownership, :except => :create
  before_filter :check_logged_in, :only => :create
  after_action :get_q_vote, :except => [:destroy]

  def create
    @answer = Answer.new answer_params
    @question = Question.find params[:question_id]
    @answer.question = @question
    @answer.score = 1
    @answer.user= @current_user
    if @answer.save
      redirect_to @question
    else
      before_render
      render '/questions/show'
    end
  end

  def edit # @question and @answer are loaded by the before filter.
    before_render
    render '/questions/show'
  end

  def update
    @answer.update answer_params
    unless @answer.errors.any?
      @answer.edited_at = @answer.updated_at
      @answer.save
      before_render
      redirect_to @question
    else
      before_render
      render '/questions/show'
    end
  end

  def destroy
    @answer.destroy
    # Yeah, trying to learn ajax in one night when the ruby docs are in coffeescript, non trivial.
    # respond_to do |format|
    #   format.html { redirect_to question_path }
    #   format.json { head :no_content }
    # end
    redirect_to @question
  end

  private
  def answer_params
    params.require(:answer).permit(:text)
  end

  def answer_ownership
    @question = Question.find params[:question_id]
    @answer =@question.answers.find params[:id]
    unless @answer.user == @current_user
      flash[:error] = "ಠ_ಠ don't edit what isn't yours ಠ_ಠ"
      redirect_to root_path
    end
  end

  def before_render #if anyone can explain to me why this isn't in rails, you can go fuck yourself.
    # and yes, I know about the gem, thankyou. I'm doing this at fucking 2am on friday and don't
    # want a deploy issue.
    @answers = @question.answers
    get_votes
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_filter :question_ownership, :only => [:edit, :update, :destroy]
  before_filter :check_logged_in, :only => [:new, :create]

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find params[:id]
    @answer = Answer.new
    @answers = @question.answers
    get_votes
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new question_params
    @question.score = 1
    @question.user = @current_user
    if @question.save
      redirect_to @question
    else
      render :new
    end
  end

  def edit
  end

  def update
    @question.update question_params
    unless @question.errors.any?
      @question.edited_at = @question.updated_at
      @question.save
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions
  end

  private
  def question_params
    params.require(:question).permit(:id, :title, :text)
  end

  def question_ownership
    @question = Question.find params[:id]
    unless @question.user == @current_user
      flash[:error] = "ಠ_ಠ don't edit what isn't yours ಠ_ಠ"
      redirect_to root_path
    end
  end

end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/questions/answers/_a_score.html.erb
<div class="q_score_bag col-xs-2 text-center">

  <% if a_vote.nil? %>
    <% up_class_string = "grey up" %>
    <% down_class_string = "grey down" %>
  <% elsif a_vote.valency == 1 %>
    <% up_class_string = "yellow up" %>
    <% down_class_string = "grey down" %>
  <% elsif a_vote.valency == -1 %>
    <% up_class_string = "grey up" %>
    <% down_class_string = "yellow down" %>
  <% end %>

  <%= link_to '❦', question_answer_voteup_path(@question.id, answer.id), :class => up_class_string %>
  <br>
  <span class="blue score">
    <%= answer.score %>
  </span>
  <br>
  <span class="weird">
  <%= link_to '¡', question_answer_votedown_path(@question.id, answer.id), :class => down_class_string %>
  <span>
</div>

app/views/questions/answers/_a_toolbar.html.erb
<div class="row a_toolbar text-right">
<% if @current_user == answer.user %>
  <span>
  &nbsp; <%= link_to edit_question_answer_path(@question.id, answer.id) do %>
    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
  <% end %>
  </span>
  <span>
    &nbsp; <%= link_to(question_answer_path(@question.id, answer.id),
                :method => 'delete',
                :data => {:confirm => 'Delete Your Answer?'}) do %>
      <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span>
    <% end %>
  </span>

<% end %>
</div>

app/views/questions/answers/_form.html.erb
<%= form_for [@question, @answer] do |f| %>

  <% if @answer.errors && @answer.errors[:user].any?%>
    <p>
      <%= @answer.errors[:user].join(', ') %>
    </p>
  <% end %>

  <fieldset class="unbordered">
    <%= f.label :text, 'Your Answer' %>
    <%= f.text_area :text, :class => "form-control", :rows => "6" %>

    <% if @answer.errors && @answer.errors[:text].any?%>
      <span>
        <%= @answer.errors[:text].join(', ') %>
      </span>
    <% end %>

  </fieldset>

  <%= f.submit 'Post Your Answer', :class => ["btn", "btn-primary", "btn-lg"]  %>

<% end %>

app/views/questions/answers/_index.html.erb
<% @answers.zip(@a_votes).to_a.sort {|a, b| b[0].score <=> a[0].score }.each_with_index do |answer_vote| %>
<% answer = answer_vote[0] %>
<% a_vote = answer_vote[1] %>
  <div class="answer--show row clearfix">
    <%= render :partial => 'questions/answers/a_score', :locals => {:a_vote => a_vote, :answer => answer} %>
    <div class="col-xs-10">
      <% if answer.id == @answer.id %>
        <%= render :partial => '/questions/answers/form' %>
      <% else %>
        <article class="answer--text clearfix">
          <div class="pull-right">
            <%= render :partial => '/questions/answers/a_toolbar', :locals => {:answer => answer} %>
          </div>
          <%= markdown answer.text %>
        </article>

        <%= render :partial => '/layouts/verbed_by',
                   :locals => {:verbed => "answered", :timeable => answer, :unlinked => false} %>


      <% end %>
    </div>
  </div>

  <hr>

<% end %>


<% if @current_user && @answer.id.nil? %>
  <%= render :partial => '/questions/answers/form' %>
<% end %>

app/views/questions/answers/edit.html.erb
<!-- I don't believe this is every used. -->


<h2 class="question--title"> <%= @question.title %> </h2>

<%= render :partial => 'q_toolbar' %>

<article class="question--text">
  <%= markdown @question.text %>
</article>

<%= render :partial => 'form' %>