config/routes.rb
# == Route Map
#
#        Prefix Verb   URI Pattern                   Controller#Action
#     questions GET    /questions(.:format)          questions#index
#               POST   /questions(.:format)          questions#create
#  new_question GET    /questions/new(.:format)      questions#new
# edit_question GET    /questions/:id/edit(.:format) questions#edit
#      question GET    /questions/:id(.:format)      questions#show
#               PATCH  /questions/:id(.:format)      questions#update
#               PUT    /questions/:id(.:format)      questions#update
#               DELETE /questions/:id(.:format)      questions#destroy
#

Rails.application.routes.draw do
  root :to => 'questions#index'

  get '/about' => 'pages#about'

  resources :questions do
    resources :answers, :only => [:create, :update, :edit, :destroy], :controller => 'questions/answers' do
      get '/voteup' => 'a_votes#up'
      get '/votedown' => 'a_votes#down'
    end
    get '/voteup' => 'q_votes#up'
    get '/votedown' => 'q_votes#down'
  end

  get '/users/edit' => 'users#edit'
  resources :users, :only => [:new, :create, :edit, :update, :show]

  get '/signup' => 'users#new'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

#  post '/answers' => 'answers#create'
#  post '/answers/:id' => 'answers#update'
#  delete '/answers' => 'answers#delete'

end

app/views/layouts/_verbed_by.html.erb
<!-- Needs locals
verbed == a string, which is a verb,
timeable has - user
             - created_at
             - edited_at, maybe
 -->
 <div class="question--dates small pull-right">
  <span>
     <%= verbed %> by
     <% if unlinked %>
       <%= timeable.user.name %>
     <% else %>
       <%= link_to timeable.user.name, timeable.user %>
     <% end %>
     at
     <%= timeable.created_at.strftime '%l:%M%P, %e/%m/%Y' %><!--
  --></span><% if timeable.edited_at.present? %><!--
  --><span>,
     edited at <%= timeable.edited_at.strftime '%l:%M%P, %e/%m/%Y' %>
  </span>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>askterix</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
  <div class="container-fluid">
    <header>

      <div class="site-title">
         ¿@₴𝝹†ər¡☓‽
      </div>

      <nav class="clearfix">
        <div class="container-fluid">
        <ul class="nav-left">
          <li>
            <%= link_to 'Home', root_path %>
          </li>
          <% if @current_user.present? %>
            <li>
              <%= link_to 'New Question?', new_question_path %>
            </li>
          <% end %>
        </ul>

        <ul class="nav-right">
          <% if @current_user %>
            <li>
              <%= link_to "Profile", @current_user %>
            </li>
            <li>
              <%= link_to "logout #{ @current_user.email }", login_path, :method => :delete%>
            </li>
          <% else  %>
            <li>
              <%= link_to "Sign up", signup_path %>
            </li>
            <li>
              <%= link_to "Log in", login_path %>
            </li>
          <% end %>
        </ul>
        </div>
      </nav>
    </header>

    <% if flash[:error].present? %>
    <h2 class="error text-center">
      <%= flash[:error] %>
    </h2>
    <% end %>

    <%= yield %>


  </div>
  <footer>
    <a href="/about">⨳</a>
  </footer>

</body>
</html>